export enum QUERY_KEYS {
  AUTH = 'AUTH',
  PROFILE = 'PROFILE',
  EMPLOYEE = 'EMPLOYEE',
  EMPLOYEE_PROFILE = 'EMPLOYEE_PROFILE',
  EMPLOYEES_LIST = 'EMPLOYEES_LIST',
  PUBLICATIONS_LIST = 'PUBLICATIONS_LIST',
  PUBLICATIONS = 'PUBLICATIONS',
  ROLES = 'ROLES',
  MUTATE_ROLE = 'MUTATE_ROLE',
  PERMISSIONS = 'PERMISSIONS',
  ADMINISTRATION = 'ADMINISTRATION'
}
