name: fitapp
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 7777:80
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: FITApp.Gateway/Dockerfile
    ports:
      - "7000:8080"
    env_file:
        - .env
  identity-service:
    container_name: identity-service
    build:
      context: .
      dockerfile: FITApp.IdentityService/Dockerfile
    env_file:
        - .env
    depends_on:
      postgres:
        condition: service_healthy
      employees-service:
        condition: service_healthy
  employees-service:
    container_name: employees-service
    build:
      context: .
      dockerfile: FITApp.EmployeesService/Dockerfile
    env_file:
        - .env
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5002/_health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 7001:5432
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 7002:27017
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongo-data:
  postgres-data:
