name: fitapp
services:
  identity-service:
    container_name: identity-service
    build:
      context: .
      dockerfile: FITApp.IdentityService/Dockerfile
    env_file:
        - .env
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: FITApp.Gateway/Dockerfile
    ports:
      - "7000:8080"
    env_file:
        - .env
